name: Test App

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: python -m nuitka app.py
           --enable-plugin=pyside6
           --include-data-dir=resources=resources
           --macos-create-app-bundle
           --macos-app-icon=resources\images\icon.png
           --output-dir=build
           --standalone
           --show-scons
           --windows-console-mode=disable
           --windows-icon-from-ico=resources\images\icon.png
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
